ktock/buildg

README.md

It's not possible. We'll work on fix this
```
go: github.com/ktock/buildg@latest (in github.com/ktock/buildg@v0.0.0-20220509061444-cd821e27d72a):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```

README: Remove install using `go install`

---

README.md
handler.go

Currently `clear` takes a line number but this should be fixed to take
breakpiont key becaue futural breakpoint can be keyed by non line number
(e.g. event name like build failure).

Fix `clear` to take breakpoint key instead of line number

---

README.md
debug.go
handler.go

`on-fail` breakpoint breaks when a step fails and allows debugging the state.
This is enabled by default and disabled by `clear on-fail`.
`b on-fail` can be used to re-enable this breakpoint.

Add `on-fail` breakpoint

---

exec_test.go
go.mod
handler.go

Allow using shell-styled quoting and escaping
e.g.
```
>>> exec sh -c "echo \"hello world\""
hello world
```

exec: allow shell-styled expression

---

break_test.go
handler.go

```
>>> b 4
>>> bp
[0]: line: Dockerfile:4
[on-fail]: breaks on fail
>>> c
Breakpoint[0]: reached line: Dockerfile:4
Breakpoint[on-fail]: caught error process "/bin/sh -c echo -n c > /" did not complete successfully: exit code: 1
Filename: "Dockerfile"
1| FROM registry2-buildkit:5000/busybox:1
2| RUN echo -n a > /a
3| RUN echo -n b > /a
*=>   4| RUN echo -n c > /
5| RUN echo -n d > /d
```

Prints all hit breaktpoints on a step

---

.github/workflows/tests.yml
README.md
main.go
main_test.go
pkg/testutil/debugshell.go

Add `--cache-reuse` option which allows sharing the build cache among invocation of `buildg debug` to make the 2nd-time debugging faster. This is useful to speed up running `buildg` multiple times for debugging an errored step.
Note that breakpoints on cached steps are ignored as of now. Because of this limitation, this feature is optional as of now. We should fix this limitation and make it the default behaviour in the future.
The build data is stored to the default common location (e.g. "/var/lib/buildg/data"). To prune the cache, user can manually remove that directory.
Here we debug a failed step at line 4 (`RUN echo fail > /`).
```Dockerfile
FROM registry2-buildkit:5000/busybox:1
RUN echo foo > /foo
RUN echo bar > /bar
RUN echo fail > /
```
1st time invocation computes all steps and …

Enable to reuse cached results

---

main.go

Thanks for this tool @ktock , It looks amazing.
Why this PR ?
avoid printing the error stacktrace 
```
root@734a148bfed0:/home/buildg/out# ./buildg debug 
context needs to be specified
main.parseSolveOpt
/home/buildg/main.go:394
main.debugAction
/home/buildg/main.go:240
github.com/urfave/cli.HandleAction
/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524
github.com/urfave/cli.Command.Run
/go/pkg/mod/github.com/urfave/cli@v1.22.9/command.go:173
github.com/urfave/cli.(*App).Run
/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277
main.main
/home/buildg/main.go:70
runtime.main
/usr/local/go/src/runtime/proc.go:255
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1581
```
Signed-off-by: Fahed DORGAA <fahed.dorgaa@gmail.com>

decrease error verbosity

---

README.md
main.go
main_test.go
pkg/testutil/debugshell.go

```console
$ buildg.sh du
WARN[2022-06-01T03:08:38Z] using host network as the default            
ID									RECLAIMABLE	SIZE
mkc2l6guvrgl5f193q9gx778u                                              	true       	2112204 B
wa8gx348tg9h2ags1hy0rfdxe                                              	true       	1351680 B
nenp1s8rlyd3azm4qr2o0qfi6                                              	true       	1347584 B
29my9ijfl16gkj3p3ipnpymjm                                              	true       	8192 B
wg4kpbve5fae4uny85cw8eddc                                              	true       	4096 B
Total:	4823756 B
$ buildg.sh prune
WARN[2022-06-01T03:08:40Z] using host network as the default            
ID									RECLAIMABLE	SIZE
wa8gx348tg9h2ags1hy0rfdxe …
```

Add prune and du subcommands 

---

debug.go
main_test.go

This commit fixes the panic which occurs when execing into the cached op with bind mounts 
```
DEBU[2022-06-28T02:23:02Z] finishing listening debug events             
panic: runtime error: index out of range [1] with length 1
goroutine 43 [running]:
main.(*handler).execContainer(0xc00028bb00, {0x12b1498, 0xc000122000}, {0xc000158f50, {0xc00023b160, 0x1, 0x1}, 0x1, {0x129ec28, 0xc00023b460}, ...})
/go/src/github.com/ktock/buildg/exec.go:130 +0xd9f
main.execCommand.func1(0xc000c7e420)
/go/src/github.com/ktock/buildg/exec.go:91 +0x52b
github.com/urfave/cli.HandleAction({0xf5ff00, 0xc0007464c0}, 0x4)
/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x111d2ab, 0x4}, {0x0, 0x0}, {0xc00023afb0, 0x1, 0x1}, {0x1137617, 0x1b}, {0x116692f, ...}, ...}, …
```

Fix panic on cached op with bind mounts

---

README.md

`buildg dap serve` doesn't take args.

README: Fix dap usage

---

.github/workflows/tests.yml
Makefile

Fixes: #55
Statically link binaries same as BuildKit https://github.com/moby/buildkit/blob/536c3fedca51112a9af39db3a850d3997766f0b9/Dockerfile#L83

Makefile: statically link binary

---

.dockerignore
.github/workflows/release.yml
.gitignore
Dockerfile
README.md
docker-bake.hcl

carrying #47 
Thanks to @developer-guy 
You can run buildg inside Docker.
You need to bind mount the build context to the container.
```
docker build -t buildg .
docker run --rm -it --privileged -v /path/to/ctx:/ctx:ro buildg debug /ctx
```
You can also use [bake command by Docker Buildx](https://docs.docker.com/engine/reference/commandline/buildx_bake/):
```
docker buildx bake --set image-local.tags=buildg
```

[Carry 47] ability to build container image

---

.dockerignore
.github/workflows/release.yml
.gitignore
Dockerfile
docker-bake.hcl

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #46 
> https://github.com/developer-guy/buildg/actions/runs/2609175895

chore: ability to build container image

---

pkg/dap/io.go

This causes recent CI flakiness

DAP: Fix io timeout is too early

---

.github/workflows/tests.yml
.golangci.yml

Also removes deprecated linters (`varcheck`, `structcheck`) https://github.com/golangci/golangci-lint/pull/3125

Bump up golangci-lint to v1.49

---

README.md
commands.go
log.go
main.go

Show build log
Usage: `log [OPTIONS]`
Flags:
- `-n value`: Print recent n lines (default: 10)
- `--all`, `-a`: show all lines
- `--more`: show buffered and unread lines
```console
$ buildg.sh debug /tmp/ctx
WARN[2022-08-30T11:22:53+09:00] using host network as the default            
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s
#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 111B done
#2 DONE 0.1s
#3 [internal] load metadata for ghcr.io/stargz-containers/busybox:1.32.0-org
#3 ...
#4 [auth] stargz-containers/busybox:pull token for ghcr.io
#4 DONE 0.0s
#3 [internal] load metadata for ghcr.io/stargz-containers/busybox:1.32.0-org
#3 DONE 1.1s
INFO[2022-08-30T11:22:55+09:00] debug session started. type "help" for command …
```

Add log command to show build logs

---

README.md
break.go
break_test.go
commands.go

Proceed to the next or the specified breakpoint
Usage: `continue [BREAKPOINT_KEY]`
Optional arg `BREAKPOINT_KEY` is the key of a breakpoint until which continue the build.
Use `breakpoints` command to list all registered breakpoints.

Allow to specify the target breakpoint on continue command

---

.dockerignore

We shouldn't have the suffix  `.m` in the released binary like the following:
```
$ buildg --version
buildg version v0.4.0.m
```

Remove `.m` suffix from release binary

---

.github/workflows/release.yml
docker-bake.hcl

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
use [gha cache](https://github.com/moby/buildkit#github-actions-cache-experimental) for speeding up the containerize process
https://github.com/developer-guy/buildg/actions/runs/3050865102
/cc @ktock

chore: use cache-to & cache-from options with GHA mode

---

.github/workflows/release.yml

hub has been deprecated: https://github.com/actions/runner-images/issues/8362

ci: release: migrate `hub` to `gh`

---

.github/workflows/tests.yml
Dockerfile
README.md
docker-bake.hcl
exec_test.go
go.mod

- Bump the remaining Go 1.22 references to 1.23
- Update toolchain to 1.23.8
- Update Docker images in tests to use ubuntu:24.04
- Update required Go version in README

chore: bump remaining go 1.22 references to 1.23

---

.github/workflows/release.yml
docker-bake.hcl

v0.5.0 release failed because of this. Let's skip v0.5.0 and release v0.5.1 soon.
https://github.com/ktock/buildg/actions/runs/14663800600/job/41153836282

CI: Fix "containerize" CI to work on the latest bake
